CREATE TABLE DICT
(
    DICT_ID VARCHAR2(36) PRIMARY KEY NOT NULL,
    DICT_TYPE VARCHAR2(50),
    DICT_TYPE_NAME VARCHAR2(50),
    DICT_CODE VARCHAR2(50),
    DICT_VALUE VARCHAR2(50),
    CRT_TIME VARCHAR2(30),
    ALT_TIME VARCHAR2(30)
);
COMMENT ON COLUMN DICT.DICT_ID IS '数据字典ID';
COMMENT ON COLUMN DICT.DICT_TYPE IS '数据字典类型';
COMMENT ON COLUMN DICT.DICT_TYPE_NAME IS '数据字典类型名称';
COMMENT ON COLUMN DICT.DICT_CODE IS '数据字典编码';
COMMENT ON COLUMN DICT.DICT_VALUE IS '数据字典数值';
COMMENT ON TABLE DICT IS '数据字典表';