CREATE TABLE "USER"
(
    USER_ID VARCHAR2(36) PRIMARY KEY NOT NULL,
    USER_CODE VARCHAR2(100),
    PASSWORD VARCHAR2(500),
    USER_TYPE VARCHAR2(2),
    STATUE VARCHAR2(2),
    USER_NAME VARCHAR2(50),
    USER_NAME_BAK VARCHAR2(50),
    USER_PHOTO_URL VARCHAR2(500),
    MOBILE VARCHAR2(20),
    SEX VARCHAR2(2),
    CRT_TIME DATE,
    ALT_TIME DATE
);
CREATE UNIQUE INDEX USER_USER_ID_uindex ON "USER" (USER_ID);
COMMENT ON COLUMN "USER".USER_ID IS '用户ID';
COMMENT ON COLUMN "USER".USER_CODE IS '登录账号';
COMMENT ON COLUMN "USER".PASSWORD IS '登录密码';
COMMENT ON COLUMN "USER".USER_TYPE IS '登录用户类型';
COMMENT ON COLUMN "USER".STATUE IS '登录状态';
COMMENT ON COLUMN "USER".USER_NAME IS '用户姓名';
COMMENT ON COLUMN "USER".USER_NAME_BAK IS '用户称号';
COMMENT ON COLUMN "USER".USER_PHOTO_URL IS '用户头像路径';
COMMENT ON COLUMN "USER".MOBILE IS '用户手机号码';
COMMENT ON COLUMN "USER".SEX IS '用户性别';
COMMENT ON TABLE "USER" IS '登录用户表';