create table CRAWLER_ACCOUNT
(
	ID VARCHAR2(36) not null
		primary key,
	WEB VARCHAR2(100),
	WEB_NAME VARCHAR2(100),
	ACCOUNT VARCHAR2(50),
	PASSWORD VARCHAR2(50),
	ALT_DATE DATE,
	CRT_DATE DATE,
	FLAG VARCHAR2(2)
)
/

comment on table CRAWLER_ACCOUNT is '爬虫账号'
/

comment on column CRAWLER_ACCOUNT.ACCOUNT is '账号'
/

comment on column CRAWLER_ACCOUNT.PASSWORD is '密码'
/

comment on column CRAWLER_ACCOUNT.FLAG is '0-未启用；1-已启用'
/
ALTER TABLE CRAWLER_ACCOUNT ADD UPD_USER VARCHAR2(50) NULL;
ALTER TABLE CRAWLER_ACCOUNT ADD CRT_USER VARCHAR2(50) NULL;

ALTER TABLE CRAWLER_ACCOUNT ADD UPD_NAME VARCHAR2(50) NULL;
ALTER TABLE CRAWLER_ACCOUNT ADD CRT_NAME VARCHAR2(50) NULL;
ALTER TABLE CRAWLER_ACCOUNT RENAME COLUMN ALT_DATE TO UPD_TIME;
ALTER TABLE CRAWLER_ACCOUNT RENAME COLUMN CRT_DATE TO CRT_TIME;