CREATE TABLE CRAWLER_URL_INFO
(
  id varchar2(36) PRIMARY KEY NOT NULL,
  ALT_DATE DATE,
  CRT_DATE DATE,
  URL VARCHAR2(500),
  URL_NAME VARCHAR2(200),
  TYPE varchar2(100),
  TYPE_NAME VARCHAR2(100)
);
COMMENT ON TABLE CRAWLER_URL_INFO IS '爬虫地址字典表';
