
CREATE TABLE MOVIE_USER
(
  ID            VARCHAR2(36) PRIMARY KEY NOT NULL,
  MOVIE_ID      VARCHAR2(36),
  USER_ID       VARCHAR2(36),
  SCORE         VARCHAR2(2),
  SHORT_COMMAND CLOB,
  WATCH_AFTER_TIME     TIMESTAMP(6)  default NULL,
  WATCH_BEFORE_TIME     TIMESTAMP(6)  default NULL,
  STATE         VARCHAR2(2),
  CRT_TIME     TIMESTAMP(6)  default NULL,
  CRT_USER     VARCHAR2(255) default NULL,
  CRT_NAME     VARCHAR2(255) default NULL,
  CRT_HOST     VARCHAR2(255) default NULL,
  UPD_TIME     TIMESTAMP(6)  default NULL,
UPD_USER     VARCHAR2(255) default NULL,
UPD_NAME     VARCHAR2(255) default NULL,
UPD_HOST     VARCHAR2(255) default NULL
);
COMMENT ON COLUMN MOVIE_USER.STATE
IS ' (1-"想看"、2-"看过"、3-"在看")';
COMMENT ON TABLE MOVIE_USER
IS '电影和用户关系表';
COMMENT ON COLUMN MOVIE_USER.WATCH_AFTER_TIME
IS '看过的时间';
COMMENT ON COLUMN MOVIE_USER.WATCH_BEFORE_TIME
IS '想看的时间';
CREATE UNIQUE INDEX MOVIE_USER_ID_uindex
  ON MOVIE_USER (ID);