
CREATE TABLE MOVIE_COUNTRY
(
  id varchar2(36) PRIMARY KEY NOT NULL,
  country_code varchar2(10),
  movie_id varchar2(36),
  CRT_TIME TIMESTAMP(6)  default NULL,
  CRT_USER VARCHAR2(255) default NULL,
  CRT_NAME VARCHAR2(255) default NULL,
  CRT_HOST VARCHAR2(255) default NULL,
  UPD_TIME TIMESTAMP(6)  default NULL,
  UPD_USER VARCHAR2(255) default NULL,
  UPD_NAME VARCHAR2(255) default NULL,
  UPD_HOST VARCHAR2(255) default NULL
);
COMMENT ON TABLE MOVIE_COUNTRY IS '电影国家信息表';