CREATE TABLE MOVIE_TYPE
(
  ID VARCHAR2(36) PRIMARY KEY NOT NULL,
  MOVIE_ID VARCHAR2(36),
  TYPE VARCHAR2(10),
  CRT_TIME TIMESTAMP(6)  default NULL,
  CRT_USER VARCHAR2(255) default NULL,
  CRT_NAME VARCHAR2(255) default NULL,
  CRT_HOST VARCHAR2(255) default NULL
);
COMMENT ON TABLE MOVIE_TYPE IS '电影信息类型表';